global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Правила алертов
rule_files:
  - "alertmanager-rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Web application
  - job_name: 'web'
    metrics_path: /metrics
    static_configs:
      - targets: 
          - 'web:8080'
    dns_sd_configs:
      - names:
          - 'web'
        type: 'A'
        port: 8080

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  # cAdvisor (Docker metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Node Exporter (Host metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']